name: Deployment to Pantheon via ACLI

on:
  push:
    branches:
      - acli-cd

jobs:
  deployment_blt:
    name: "Deploy code to Pantheon via BLT"
    timeout-minutes: 7
    runs-on: ubuntu-latest
    env:
      # Variables to connect to Pantheon.
      PANTHEON_ENVIRONMENT: ${{ vars.PANTHEON_ENVIRONMENT }}
      PANTHEON_EMAIL: ${{ secrets.PANTHEON_EMAIL }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install PHP.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Install Node for theme installation.
      - name: Node js installer
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: web/themes/custom/fewsnews_theme/package-lock.json

      # Configuring private ssh key for code deployment to Pantheon.
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Terminus installing
        run: |
          cd
          mkdir -p ~/terminus && cd ~/terminus
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.2.1/terminus.phar --output terminus
          chmod +x terminus
          ./terminus self:update
          sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
          terminus auth:login --email=$PANTHEON_EMAIL --machine-token=$PANTHEON_MACHINE_TOKEN

      - name: ACLI install
        run: |
          curl -OL https://github.com/acquia/cli/releases/latest/download/acli.phar
          chmod +x acli.phar
          mv acli.phar /usr/local/bin/acli

      # Configuring SSH config to auto-adding not knowing fingerprints without asking.
      - name: Fingerprint configuring
        run: |
          sudo chmod o+w /etc/ssh/ssh_config
          echo "StrictHostKeyChecking accept-new" >> /etc/ssh/ssh_config

      - name: Git config
        run: |
          git config --global user.email "cd-script@github.com"
          git config --global user.name "CD Script"

      - name: Artifact Deployment module install
        run: |
          composer require 'drupal/artifact_deployment:1.0.x-dev@dev'

      - name: Build and Deploy the artifacts
        env:
          PANTHEON_SITE_GIT_URL: "ssh://codeserver.dev.bf0a27cb-4a57-47b8-aab6-064b573610c1@codeserver.dev.bf0a27cb-4a57-47b8-aab6-064b573610c1.drush.in:2222/~/repository.git"
          CD_SCRIPT: "TRUE"
          PATH_TO_THEME: "web/themes/custom/bootcamp_theme"
        run: |
          acli push:artifact --destination-git-urls=$PANTHEON_SITE_GIT_URL --destination-git-branch=master -v

      - name: Deploy changes to the Drupal website on Pantheon.
        run: |
          sleep 30
          terminus drush $PANTHEON_ENVIRONMENT deploy
